### ISSUE TITLE
[protection] Separate inventory-groups

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentials#1149]
Add a permission like `fe.protection.inventorygroup = ID` which will exchange the player's inventory with a different one once they enter a region with the permission.
ID can be any value - the inventories will propably be stored in PlayerInfo or as separate structure in protection-module.
The creative-inventory for gamemode-permission can then use the same backend.

**Comment by Mandelsage** [comment]
Hello again olee =)
May I ask how far you guys got with this?
On my server, one group will be forced to Adventure mod in the overworld, but will have a survival dimension of their own, to play around in. I would like to keep the two inventories separate, so that they can't go make things in their survival world and bring them back to use in the adventure mode Overworld.

**Comment by olee** [comment]
This is fully implemented.
Just set `fe.protection.inventorygroup` to some value, for example:
`/p global zone WORLD_2 value fe.protection.inventorygroup survival`

**Comment by Mandelsage** [comment]
Okay, awesome, thank you. I've just set it up and seems to be working
perfectly. Really happy with FE. Got over 90 mods on a server, going to
have different modes for different groups in different dimensions and I've
been able to set everything up that I need so far. Great work, sir!
