### ISSUE TITLE
Inventory interaction permissions (chests, etc.)

### ISSUE THREAD

**Issue by auron117** [ForgeEssentials/ForgeEssentials#1394]
Hey,

Was wondering if there was a permission to deny block place and break but allow chest entry?

Also was wondering if there would be a version of MultiversePortals being added. I am currently using /mwtp command with @p(player) to teleport using command blocks. Command blocks are finicky however and it would be nice to have a more stable way to TP. 

Thanks for any help or suggestions

Auron117

**Comment by luacs1998** [comment]
There are portals implemented, but I'm not entirely sure on how to create them.

Currently there is no such chest-entry-only permission, but we can consider this a request...

**Comment by auron117** [comment]
Thanks for the quick response. Is there a way to perhaps select a chest
with the wand and allow access? I know its a long shot

**Comment by luacs1998** [comment]
No such permission exists.

**Comment by olee** [comment]
For portals use the `/portal` command (it comes with help-text if you enter just `/portal`).
Placing / breaking blocks can of course be controlled individually (see protection guide).
But we have no inventory interaction permissions yet because of missing events (iirc).
The only thing you can do is to deny all interaction with the chest.
But you could maybe place a hopper at the chest so players can put something into the chest, but only a certain player group is allowed to access the chest directly.

**Comment by luacs1998** [comment]
We should add events for inventory open and inventory close.

**Comment by luacs1998** [comment]
Replaced by #1952
