### ISSUE TITLE
Zone permissions damageby persists even outside the zone

### ISSUE THREAD

**Issue by BossLetsPlays** [ForgeEssentials/ForgeEssentials#1657]
So I need to disable damage for my spawn zone on my server, however when I do that if a player was in spawn during his session then the no damage follows him or her. And they don't start taking damage until they reconnect to the server. All other permissions so far work correctly but this one follows the players.

To stop damage in the spawn I do `/p group _ALL_ zone spawn deny fe.protection.damageby.*`

Even doing `/p global value fe.protection.damageby.* true` does not override it.

Like I said, all the other permissions (i.e block placing and destroying) work fine, so I know its not a problem with the selection or area I defined.

I am using version 1.4.0 for 1.7.10 if that helps.

**Comment by olee** [comment]
This sounds interesting.
There *should* be no way that this permission "follows" the players.
In fact it would be really difficult to achieve something like that.
I suspect there is instead something wrong with the reported player position when damage is checked which is why it checks the permission at a wrong place.

Please try using `/p debug` to see the results of the permission checks when a player is attacked inside / outside the spawn zone. Mainly the result when outside the spawn area will be interesting. It would probably best if you post a screenshot of the lines outputted or copy them somehow (e.g. from the client log for example).

**Comment by BossLetsPlays** [comment]
Here is a screenshot from in the spawn: http://prntscr.com/7y1vg2
And outside the spawn: http://prntscr.com/7y1v8h

**Comment by olee** [comment]
Ok so the second screenshot shows that the place where the permission is checked is inside the spawn zone.

The question is now: Does this mean you just set the area incorrectly (probably), or does the permission check use wrong coordinates (possible, but not very likely).

----

To check that, please do the following:
- Go outside the spawn zone (i.e. the same place as in the second screenshot)
- Run `/p list zones`

It should list the zones you are currently inside of. If it shows you the spawn area, you definitely set the spawn area incorrectly, making this a simple thing to fix. If not, I will need to start some investigation on my own.

----

Another thing I can recommend:
- Add the ForgeEssentials client mod to your own client (if you use a modpack, it's enough if you just copy it inside your own client)
- Run `/area select spawn`

This should set the WE selection to the configured area and because of the ForgeEssentials client, it should be rendered into the world for you like [that](http://forgeessentials.com/wp-content/uploads/2015/07/WorldEdit_FE_CUI.png).

**Comment by BossLetsPlays** [comment]
Yes I was outside the spawn. And the `/area select spawn` showed the correct area. And like I said so far other permissions work fine, it just seems to be the damage permissions that follow the player IF the player had visited the spawn some time during his play session.. once the player reconnects he can start taking damage again, but if he dies and respawns at the spawn then he becomes immortal again.

**Comment by olee** [comment]
Ok this is really weird then. What did `/p list zones` show from outside spawn? Did it list spawn or not?

If not, then this is definitely an issue with wrong positions for the check.
I'll start invenstigating this.

**Comment by BossLetsPlays** [comment]
When I do that command all I get outside of spawn is `WORLD_0, _SERVER_, _ROOT` and thats all

**Comment by olee** [comment]
Ok - I will investigate this in a few hours (need to get to Uni right now) and you can expect a fix in the next 6h or so.

**Comment by luacs1998** [comment]
Is this still an issue?

**Comment by olee** [comment]
I don't know - I never got to try it out in the end because I got busy with other stuff and kinda forgot it.
Sorry.

@luacs1998 you could try it out of course - it's not that complicated.

**Comment by luacs1998** [comment]
I'll see what I can do while you're away.

**Comment by olee** [comment]
I think this might have just been incorrectly set permissions or some other weird thing.
Will close this until someone can report this problem still happening.
