### ISSUE TITLE
AFK Timeout not persisting across restarts

### ISSUE THREAD

**Issue by xSparky911x** [ForgeEssentials/ForgeEssentials#1738]
I have tried setting afk.timeout both in the game and in the config but when server restarts it gets reset to 480 and kicks. I understand you can bypass with permissions but whats the point in setting it in the config if it doesn't stick?

**Comment by olee** [comment]
Hm this sounds interesting.
Could it be you set it while the server is running?

**Comment by xSparky911x** [comment]
Yes it is set with the server running. Why would a server reset the config back to the previous state after a restart though? Also what would be the point of having the ability to change a setting live in the game with a command if it reverts or the ability to reload the config after changing the setting VIA the config file.

**Comment by Zethalion** [comment]
I can confirm /afk won't work at my server either. No matter what I put in the config file or using /fesettings

1.7.10 v1.4.0 and up till build 935. Haven't tried build 941 yet

**Comment by luacs1998** [comment]
Does this happen for other settings in settings.cfg?

**Comment by luacs1998** [comment]
I have managed to diagnose this issue - somehow the value in settings.cfg is being overridden by the default. This is because the default permprop values are register AFTER the values are retrieved from settings,cfg,

A fix I have in mind is to register commands BEFORE throwing the FEModuleServerPostInitEvent. @olee may I proceed with that?
