### ISSUE TITLE
Explosion block whitelist? Only stone is 'explodeable'

### ISSUE THREAD

**Issue by JackTheRedCreeper** [ForgeEssentials/ForgeEssentials#1886]
Is this possible? I'd love to have this so only cracked stone bricks and the like would be broken by explosions. However, after reading some stuff (from two years ago..), you guys are limited to what Forge allows you.

For example, I can't break grass or stone manually, but TNT can blow it up. I want TNT to not be able to blow up stone, only, or to only be able to blow up stone. Any info?

Edit: Yeah, it's low priority, yet it's been something I've been looking for for a few months ;~;
If anyone knows a mod or something that can do this (via blast resistance or something), it'd be great.

**Comment by olee** [comment]
Yeah, easily doable, as we already have an explosion permission.
We could extend / modify this to allow checking for individual blocks.
However I need to check if we can do this by default or only when using a config option because of performance impact.

@luacs1998 good you noticed yourself, that we don't really need a hook for this :smirk:

**Comment by JackTheRedCreeper** [comment]
Thank you for the information! I really wanted a half-destroyable map since time ago, with Flan's mod. Imagine blowing up a wall with C4, without being able to dig a huge hole in the ground :D

**Comment by JackTheRedCreeper** [comment]
Is it done? I've seen a post in the website about new explosion permissions but I dunno, and I also have a question, does it work with mod blocks?

**Comment by luacs1998** [comment]
This build: http://ci.forgeessentials.com/job/FE/1048/

We can't configure different entities yet.

**Comment by olee** [comment]
@JackTheRedCreeper in the newest build it will work.
And the other thing with explosion-"owners" should work now, too.
Grab the latest builds from here: http://ci.forgeessentials.com/job/FE/

**Comment by JackTheRedCreeper** [comment]
Woo! Many thanks!

**Comment by JackTheRedCreeper** [comment]
Can I somehow make creepers only blow up, let's say, planks? As an example, I'll tune it to whatever needs I have.

**Comment by olee** [comment]
Well - as owners you can just use either players (groups or individuals) or set it globally.
I will add a NPC user to allow setting it for just mobs (wait for next commit)
````
/p user $NPC deny fe.protection.explode.*
````

**Comment by JackTheRedCreeper** [comment]
Aww, ok, I thought I could do something like $Creeper to fine tune it, but no prob.

**Comment by olee** [comment]
Well... in theory I could do this.... if you really think you need it and that it could be useful to others, too....

**Comment by JackTheRedCreeper** [comment]
I dunno. It'd be cool to have C4s from Flan's mod break walls but not grenades. Prolly if you're using some mod that adds extra explosives and some sort of breaching charge, you could use it...
I don't want to bother you much, and as I'm not using a server (a friend was working on one but he quit :/), I don't really need this

**Comment by olee** [comment]
What you are talking about is not what we talked about before.
You are talking of explosions caused by different sources - this is not possible and has nothing to do with what I was saying before.

What I said was about distinguishing between different mobs as the source **causing** the explosion - and with that I mean the one who started (i.e. which player / a creeper) it and not what (TNT, Ghast shot, etc.).

To do the thing you talked about, we would need a completely different permission.
And that one would either disable or allow the explosion completely.
You wouldn't be able to just disable block damage.

**Comment by JackTheRedCreeper** [comment]
Well, as I don't have any need for this (Sadly!), I won't bother you anymore with it. Good luck! :)
