### ISSUE TITLE
How to bypass authentication for specific users like FakePlayer 

### ISSUE THREAD

**Issue by MineMine** [ForgeEssentials/ForgeEssentials#1899]
This message appears repeatedly 

[ForgeEssentials]: Fakeplayer FakeThaumcraftGolem: Login required. Try /auth help.

[ForgeEssentials]: Fakeplayer [BP Deployer]: Login required. Try /auth help.

How can I solve this problem?

**Comment by MineMine** [comment]
/auth setpass <FakePlayer> <pass> is not working

**Comment by MineMine** [comment]
Thanks for fast response

I always appreciate to FE dev team :D

**Comment by MineMine** [comment]
Hmm how can I apply this patch to resolve problem? 

I had already downloaded the latest snapshot in jenkins and replace from old version

but error is still showing :(

this time only showing up this 

[ForgeEssentials]: Fakeplayer FakeThaumcraftGolem: Login required. Try /auth help.

sorry for my bad english

**Comment by luacs1998** [comment]
Will need to find a better solution then...

**Comment by MineMine** [comment]
Other Fakeplayer (Like Buildcraft and Railcraft) is working nicely but only ThaumCraft Golem is the problem hmm... I'm sorry

**Comment by olee** [comment]
@luacs1998 your fakeplayer tweak is useless, because REAL fakeplayers are not affected by it.
Thaumcraft golems probably did the same thing as LittleMaidMob mod and programmed their own EntityPlayerMP.
I guess it should work if you verify, that the player class **excatly** matches `EntityPlayerMP` (e.g., **no** instanceof, but instead using `player.getClass().equals(EntityPlayerMP.class)`).

**Comment by luacs1998** [comment]
I was going to ask you to handle that :)

**Comment by luacs1998** [comment]
Should be fixed in https://github.com/ForgeEssentials/ForgeEssentials/commit/c6c594906473801f7988b3e7d191349ccab2af04

**Comment by olee** [comment]
Oh yeah, forgot to close this.
Thanks
