### ISSUE TITLE
Problem with rcon because of FE

### ISSUE THREAD

**Issue by lospiros** [ForgeEssentials/ForgeEssentials#1929]
when i've made my modded server i've make a rcon connection with my website to send command etc..
After a week i found FE (pretty nice server-side mod anyway) but since i've installed FE any commands work, i see on log file that the connection success but nothing is send... and i'm sure that is caused by FE (try tests with and without)
i use this script found on github : https://gist.github.com/tehbeard/1292348

**Comment by olee** [comment]
This was fixed in one of  the last versions.
RCON uses another command sender than the console.
You can now actually control permissions for RCON separately.
Also I can recommend you to use FE's remote API instead of rcon which provides many more features, works more reliably and allows permission controlled multi-user login.
