### ISSUE TITLE
Wildcard permission not recursing properly

### ISSUE THREAD

**Issue by DarkMorford** [ForgeEssentials/ForgeEssentials#1955]
I'm running an Infinity Evolved 2.2.2 server with ForgeEssentials 1.4.3.1021 and Dynmap 2.1 added, and I'm having issues with some of the interactions. I'm part of the `_OPS`, `_PLAYERS_`, and `_ALL_` groups on the server. Here are the relevant configs:

`_ALL_.txt`
```
fe.internal.group=true
fe.internal.group.name=players
fe.internal.group.priority=0
dynmap.*=false
fe.remote.chat.send=false
some.test.permission=true
worldedit.*=false
```

`_OPS_.txt`
```
fe.internal.group=true
fe.internal.group.priority=50
fe.internal.prefix=[&cOP&f]
worldedit.*=true
```

`_PLAYERS_.txt`
```
fe.internal.group=true
fe.internal.group.priority=1
fe.remote.chat.send=true
```

My understanding is that this should prevent anyone on the server from using any DynMap commands, and yet they all seem to be available. I did `/p test dynmap.marker.sign` with debugging turned on and got this output:
```
fe.perm = true
  zone [_ROOT_] group [_OPS_]
fe.perm = true
  zone [_ROOT_] group [_OPS_]
fe.perm.test = true
  zone [_ROOT_] group [_OPS_]
dynmap.marker.sign = null
  permission not set
dynmap.marker.sign = true (not set)
```

**Comment by olee** [comment]
Dynmap does not provide any access to permissions for forge.
Because of that you can only allow access to the commands in general.
Check your own [PermissionList.txt](https://github.com/ForgeEssentials/ForgeEssentials/wiki/PermissionList.txt) and you should find something like `command.dynmap` which is the permission you will need to control.

Edit: Ok when I checked your post again, I saw your `/p debug` output actually showing a `dynmap.marker.sign` permission which is quite interesting (afaik a FE permission implementation for dynmap does not exist yet). Can you tell me which dynmap you used (link to download)?

**Comment by olee** [comment]
When I test it myself with dynmap installed, it shows up as `command.dynmap` when I use `/dynmap`.

**Comment by DarkMorford** [comment]
I'm using the currently-recommended Dynmap for 1.7.10, which is at [CurseForge](http://minecraft.curseforge.com/projects/dynmapforge/files/2223999).

There's also an [old issue](https://github.com/webbukkit/dynmap/issues/1253) on the Dynmap project stating that it supported ForgeEssentials as of version 1.7.1. So unless they dropped that support in the 2.x branch, I would expect that those hooks are still there.

**Comment by luacs1998** [comment]
Removed in 2.x by the looks of it.

**Comment by DarkMorford** [comment]
I'm also running into an issue where Dynmap sign markers aren't being picked up, even though it's turned on in the config.

This may or may not be related to the current permissions issue, but I wanted to make a note of it. I'll hold off on opening a separate issue until this one is resolved.

**Comment by olee** [comment]
Ok so I will close this as this is not an FE issue.
You can try poking around Dynmap devs, if they would kindly support FE permissions again.

**Comment by rfcMike** [comment]
Hey - Dynmap dev (singular) here - sorry for slow response, but I've been largely idle on the modding side for a few months (due to other obligations).  I'll be kicking back in to gear by the end of the month (finishing the course sequence I've been working since last spring), and will make a point of checking this out (along with working on a Sponge-specific Dynmap)

**Comment by mikeprimm** [comment]
Hey - Dynmap dev (singular) here - sorry for slow response, but I've been largely idle on the modding side for a few months (due to other obligations). I'll be kicking back in to gear by the end of the month (finishing the course sequence I've been working since last spring), and will make a point of checking this out (along with working on a Sponge-specific Dynmap)

**Comment by olee** [comment]
Sounds great!
If you need any help implementing permissions, just ask!
