### ISSUE TITLE
Question about scripting (auto shutdown script)

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentials#1958]
hey guys :)

i want to use your powerful scripting module for auto-shutdown now.

i have seen several methods like timeout, starttimeout and i guess i have to use the login folder so the commands will be executed on server startup.

my question:
is there a method to shutdown server on a specific time or do i have to use the trimeout method ?
can you give me a little example ? perhaps something with @realtime argument ?!

thanks in advance!

greetings

-jogi

**Comment by luacs1998** [comment]
You can use the "start" folder to run scripts when the server starts.

We don't really have a "run script at specific time" feature, so I'll consider this a request.

**Comment by olee** [comment]
There are some ways to do this...
However there are a few reasons against this:
 1. If your server is properly set up and has no bad mods that cause memory leaks, there is no need to restart your server
 2. If you stop your server with FE, it has to be restarted by your system in some way anyway
 3. 2. means you will probably run your server (linux) in a `screen` with a script that restarts it when it shuts down
 4. Because of 3. you can just setup a cron job that sends the `/stop` command to the server screen from time to time

= There are already simple solutions to this problem and FE could only **stop** the server anyway, which is why I would recommend you to set it up another way.

PS: If you still want to do it in FE there are two ways:
 1. Create the following script in `./ForgeEssentials/Scripting/cron`  
  (However the time it shuts down always depends on when it was started)
````
# 86400
confirmall Server is going to restart in a minute!
timeout 60000 /stop
````
 2. Create a permission schedule to set some permission `servercanshutdown` to true at a certain time and create a script that runs every minute or so to check that permission as a flag and shut down the server. This will allow you to have the server restart at the exact time you specified.

**Comment by jogi01** [comment]
wow thx for the detailed infos!

i have already written a loop in linux which auto restarts server if it shuts down.. 
sending the stop command to the screen is a good solution i think i will do so because i want exactly sepcify the time..

thank you very much indeed!
