### ISSUE TITLE
Mod Spawn Overriding

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1962]
I need a 1.7.10 release of forge essentials that allows me to completely override mob spawns. I used to use just another spawner but lately it isn't working. The code is open source I guess also it would be awesome if you one of you could fix it a well.

My mod-pack is tremendous and mods like Advent of Ascension and Lycanites don't have proper spawn limiting.

Here is a link to JAS https://github.com/ProjectZulu/JustAnotherSpawner/issues/154

**Comment by aschmois** [comment]
If you look at the wiki, you can use permissions to limit the spawning of each mob to true or false in a certain area. If you're looking for a more complex solution, where you set a percentage for the spawn rate, I'm afraid you're out of luck. It's not simple to limit the spawnrate of custom mobs because they could be overriding the spawning themselves. Until a more active dev answers this is the best I can do for you.

**Comment by DPxKnightxZero** [comment]
Thank you.
