### ISSUE TITLE
Unsupported mixin class version 51 - and some other mixin questions.

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1964]
error in code - https://gist.github.com/DPxKnightxZero/90f264087f8a3023737c

(edit by luacs: I seem to have accidentally hijacked this thread to ask some mixin questions. My apologies, DPxKnightXZero)

**Comment by luacs1998** [comment]
Same as #1963

**Comment by DPxKnightxZero** [comment]
It has not been fixed then.

**Comment by DPxKnightxZero** [comment]
http://ci.forgeessentials.com/job/FE/1131/ That was the version I grabbed. with the new thread!

**Comment by luacs1998** [comment]
I will not have any more of your nonsense. This is spam and nobody likes spam.

**Comment by DPxKnightxZero** [comment]
What do you mean user error? I have done nothing I am using latest forge latest java and latest fe ... how is this my fault? Sorry if your frustrated and you should know better than to think after all you have done for me I would start spawmming the fe team. In the future I will not be reporting things because I do not wish to damage the relationship I have shared with the fe team these last 6 months.

**Comment by DPxKnightxZero** [comment]
Alright has been fixed you should probably warn users they have to manually point to Java 8u71 to make it happy.

**Comment by DPxKnightxZero** [comment]
Full Clientside Log -> https://gist.github.com/DPxKnightxZero/415eaf2d25e754364e74
Full mod list - > https://gist.github.com/DPxKnightxZero/beb493b33933e49f9e53

**Comment by DPxKnightxZero** [comment]
Only appears client-side. Server-side the issue is gone.

**Comment by DPxKnightxZero** [comment]
Feel free to be upset it is still not gone
https://gist.github.com/DPxKnightxZero/76d4e7450bd8bda63b92

**Comment by DPxKnightxZero** [comment]
Crashes server spams this error. Only started a small while ago!

**Comment by luacs1998** [comment]
@mumfrey I'm out of ideas.

**Comment by Mumfrey** [comment]
You are trying to use mixin classes compiled for java 1.8 but have not set the compatibility level to `JAVA_8`, from the log file it looks like [the level is being set to "51" for some reason](https://gist.github.com/DPxKnightxZero/76d4e7450bd8bda63b92#file-gistfile1-txt-L121)

**Comment by Mumfrey** [comment]
Just for your info, a new stable is coming up. What basically happened is that something I can't currently support needed to happen in a hurry, so all versions after 0.4.5 have been snapshots because they contain a feature intended to be temporary. The [multiphase](https://github.com/SpongePowered/Mixin/commit/81414121a50cdd94e4da7318575d6a309d8c5481) branch will be completed soon and when that's merged the temporary code can go away and it'll be stable release again.

FYI: the main implication of this from library user's point of view is that instead of doing:

    MixinEnvironment.getXXXEnvironment().addConfiguration("blah.json");

you will do:

    MixinEnvironment.addConfiguration("blah.json");

and instead specify the target phase/environment inside the config file. (The old method will stay around for a while, it'll just be marked deprecated). The reason being, the mixin library will start a new phase at more arbitrarily defined points, such as immediately after a mod is injected. In the config you will be able to specify either a raw phase name (eg. `INIT` or `DEFAULT`) **or** a set of criteria which can be used to identify the phase (eg. `POSTINJECT(modid=mod_id_here)`) which will finally let mixins target mods.

**Comment by luacs1998** [comment]
Thanks a lot for the input. So I would set `MixinCompatibilityLevel=JAVA_7` in my manifest?

On a side note, we might be planning to move away from the Mixin framework in favour of a (more crude, I must say) [direct-patching bytecode system](https://github.com/ForgeEssentials/ForgeEssentials/tree/develop/src/main/java/com/forgeessentials/core/preloader/asminjector), though.

(I think it was something along the line of olee wanting to do scattergun mixins - something that you threw out a while ago)

**Comment by Mumfrey** [comment]
> Thanks a lot for the input. So I would set MixinCompatibilityLevel=JAVA_7 in my manifest?

That is correct

> On a side note, we might be planning to move away from the Mixin framework in favour of a (more crude, I must say) direct-patching bytecode system, though I'm currently leaning to stay on mixins for now.

So he just took a load of my ideas and concepts from Mixin? I feel pretty upset by that but I guess there's not much I can do. :disappointed: Especially injectors, the work on that goes back to LiteLoader (as in fact does pretty much all of Mixin) and has been brought over to and polished in Mixin.

> I think it was something along the lines of olee wanting to do scattergun mixins - something that you threw out a while ago (SpongePowered/Mixin#69).

That's exactly what the entire multiphase overhaul is designed to address, it simply wasn't possible under the old regime because the passes simply didn't allow it. However we do really need it in sponge so I've been overhauling the library to support it.

> Because I'm not really looking forward to having to re-implement all our mixins currently, and (personally) I'd like to have a more stable framework that won't crap out with other mods after the fastcraft debacle, it'd be nice if you could give me an update on whether something like that's still in the pipeline.

Yes, you have to realise that I'm both a die-hard pragmatist and a stickler for ensuring that things are as stable as they physically can be. That means that I just won't compromise to squeeze in a quick extra feature if it jeopardises the overall stability of the platform, and/or can't ever be guaranteed to play nice with other mods. Mixin is designed from the ground up on priciples of "do no harm" and the featureset is deliberately limited in order to achieve that goal as effectively as possible. This does mean however that progress on new features is slower than some people would like, but I want users to be able to trust the library and I can only realise that if things are carefully planned out.

This does mean that in the short term I will generally refuse to add certain things, but doesn't mean they're ruled out permanently. One example is mixing into (unknown) classes which directly implement an interface. Under the old system, this simply wasn't possible because there was no way to prepare for and validate these classes. The multiphase overhaul makes this possible, amongst other things.

If you choose to go your own way that's up to you, but as far as I'm concerned my mission is to provide a library that mods can depend on. One which makes the horrific mess that is the slew of awful transformers out there in the wild just a little bit less awful. I consider that I've failed in some way if users feel the need to abandon it, though I do understand that the rate of accretion of new features is frustrating to some.

**Comment by Zidane** [comment]
All I'll say at looking at that develop branch is....just....wow.

Best of luck to you.

**Comment by mcsnetworks** [comment]
Woah,

Wait just a damn minute.  You don't copy / paste someones works, EVER...

https://github.com/ForgeEssentials/ForgeEssentials/tree/develop/src/main/java/com/forgeessentials/core/preloader/asminjector

That is a direct copy/paste from Sponge's Mixin library.

**Comment by Mumfrey** [comment]
Hey guys, I appreciate you weighing in but in all honesty they are perfectly within their rights to dupe the code/concepts, when I made the choice to pull this functionality out of liteloader I knew I was taking it from an All Rights Reserved environment and putting it in an open source one, it's just the way it goes.

I'm just upset (literally, quite sad) that it was felt necessary to do so, and I think that's my fault for not making the roadmap clearer. As you all know Mixin is a bit of a personal mission for me, so I feel greatly disappointed when it doesn't measure up.

> Wait just a damn minute. You don't copy / paste someones works, EVER...

It's MIT licensed, so even if it were a direct copy/paste (which some is, but not all, it's mainly the actual idea/names of classes (eg. `InjectionPoint`, `CallbackInfo`) which have been copied), the only restriction to re-use of MIT code is maintaining the copyright notice. Nobody has done anything wrong, I'm just personally a little upset by it that's all.

**Comment by mcsnetworks** [comment]
@Mumfrey you have every right to be upset.  That being said I call it as I see it.  Just because the MIT license allows it doesn't make it "right".   There is a right way of doing things and in my opinion this isn't that.

**Comment by olee** [comment]
@Mumfrey @mcsnetworks ok guys let me clear up some stuff (sorry I can only do it now - was away for work over 2 days):

First things first: I didn't copy anything of Mixin, except it's idea of using the bytecode of already written functions to inject it into existing classes.

I **did** take a look at Mixin code while I was trying to understand the `@Inject` it provides (because I couldn't find **any** documentation about it (@Mumfrey you should definitely change this and make this the primary method of modifying code instead of `@Overwrite`, because it allows soo much better control over the code).
I also **did** take a closer look at the Injection Point **annotations** and how they are parsed into objects (because I never programmed any complex annotations myself), but that's it. The code to find out where to inject stuff was also 100% written myself without ever looking at how Mixin does it.
The last thing I took a deeper look at in Mixin code was how to get local variables (which was really confusing first, but turned out to be actually quite simple).

So I can tell you, the ASM injector I wrote to use it for FE is *completely written myself* and I only used Mixin code to understand some of the concepts.
If you actually compare those two you will actually notice quite some differences (which actually happened, because I didn't pay much attention to what Mixin does, but wrote my own stuff).
For example (I think) Mixin actually injects the "injector functions" just as they are into the target class and then only generates a call statement in the target class to run those. I noticed this while writing the code to allow generating return statements into the target method (@Mumfrey correct my if I am wrong, but could it be you actually generate an exception, which you catch in the target code to do a return?).

@Mumfrey you did an awesome work on Mixin I have to say. The injector code I wrote was only created because we really needed that feature in FE - injecting code into an unknown set of classes.
However this made soo much fun to code (yes, I'm officially a coder nerd), that I wanted to make a little bit more of it and have it a bit safer. This can also be easily seen in the commit history:
 - https://github.com/ForgeEssentials/ForgeEssentials/commit/136b5e0ca87fa9677903fe762a3eb330ac53f06c added just the `attackEntityFrom` ASM transformation hardcoded - which anyone can tell sucks with it's hardcoded bytecode.
 - Then I thought why not just copy the bytecode I need from a placeholder-like function as it's done in Mixin, which should be a lot safer and cleaner. That's why I wrote just a small method injector in https://github.com/ForgeEssentials/ForgeEssentials/commit/a25cfb91cbbe2a611da914c37e0968f82cfa308a (which got refined in https://github.com/ForgeEssentials/ForgeEssentials/commit/751286628fa6f44533a6c6ec692024b0e6b7023e) to take care of it (this is also a point where it is easy to see it has not really much to do with Mixin, which works on a completely different scale)
 - In the end it was soo exiting to code this, so I just went the full way and wrote a class injector, which could do a basic subset of what Mixin is able to do in https://github.com/ForgeEssentials/ForgeEssentials/commit/be29bf6fb3a6bb40289b5f1fbc8b1359f78b2ce9
I am really sorry for offending you @Mumfrey and hope you can see, that at no point I was even trying to steal any of you intellectual property, but tried to find a solution for this problem on my own.

Now for the actually important stuff:
@Mumfrey I really love how carefully Mixin takes care of code injection and you really did something awesome there. It was only necessary in the current situation for FE, to find some other (temporary?) solution so we could continue our work.
Also - just as you already stated - it was not clear, that Mixin would ever allow injecting code into unknown classes, which was an essential feature for us.

However, with your current roadmap clear, I would love to get our injections back to use Mixin, once you support that feature we need. Also we largely have to blame sk89q for not getting a working fastcraft out there (he should hurry up and get that alpha working, or at least release a patched version of the current release that does not crash any more).
This is also the reason why I kept the annotations my code used and stuff like `CallbackInfo` largely the same as you did, in order to be able to easily migrate back to Mixin if it got the feature we needed.

In fact, I would love to work more closely with you @Mumfrey - especially regarding that feature mentioned.

PS: @mcsnetworks 
> Woah,
> Wait just a damn minute. You don't copy / paste someones works, EVER...
> https://github.com/ForgeEssentials/ForgeEssentials/tree/develop/src/main/java/com/forgeessentials/core/preloader/asminjector
> That is a direct copy/paste from Sponge's Mixin library.

You should be more careful not to come to conclusions soo quickly. This statement also offended me as I really took a lot of time to write this on my own. However I can understand, that at first it can easily look as if I just copied Mixin code. :wink:

**Comment by DPxKnightxZero** [comment]
"I never knew such a small issue; lead to such a big conversation!" Anyways I want to thank you all and let you know I will never abandon FE. I like lite loader too but at this moment I can't find a true desire or need to use it since I use the Journeymap mod. Also player has released his alpha of fastcraft and even fixed the invisible entity bug! http://files.player.to/tmp/fastcraft-1.22-ctest18.jar this one is super close to being 100% stable. Personally; I have seen no bugs to speak of.

**Comment by olee** [comment]
@DPxKnightxZero yes, but as long as those releases stay alpha, this does not really help us.

**Comment by DPxKnightxZero** [comment]
This has been fixed for a while. Closing this.
