### ISSUE TITLE
Request Important - Auto Clear

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentials#1970]
So I now have a tremendous modpack but some players are failing to collect their loot. I know there are bukkit plugins that do this but I support FE basically I am looking for a way to clear entities drops on a programable timer in seconds. My finacee is notorius for leaving treecapitated trees in a single chunk and needless to say its problematic!

**Comment by DPxKnightxZero** [comment]
Hopefully this command will have 2 major functions.

Server wide
Zone Wide
Area Wide

In secs
When server detects X amount of drops in a single chunk.

**Comment by DPxKnightxZero** [comment]
No mod does this well.

**Comment by olee** [comment]
1. Don't spam
 2. MC already clears drops after some time - even with Treecapitator this is easily manageable
 3. If you still think you need this, look for one of the many other mods that try doing this and maybe make performance even worse.
 4. If you want to do something against that with FE, create a cron-script that clears dropped entities (might be possible).
FE doesn't need such a feature where there are enough alternatives.

**Comment by DPxKnightxZero** [comment]
What alternatives??? I found one and it didn't do what I needed. Also how is this spam? luacs1998 said something similar but again I am not spamming I am asking and I don't recall making this request. (If I did I am sorry; I have trouble with memory sometimes.)

**Comment by olee** [comment]
You can editor your first post and don't need to do two more posts after that if no one replied yet!
That's what spamming means (also before you opened multiple issues for the same problem again and again).

Anyway, I told you everything about the problem already.
And because you seem to be either unable or just too lazy to search yourself:
http://minecraft.curseforge.com/projects/lagbgon
There is already one mod that can remove dropped items and it took only 1 minute of search.

I consider this topic closed for now - use this mod or one of the many others out there for the described feature.

**Comment by DPxKnightxZero** [comment]
Oh I am sorry someone actually told me its easier for them to keep track of things because I sometimes don't see other replies to just double post. In the future I won't spam.
