### ISSUE TITLE
Large Zone Issue

### ISSUE THREAD

**Issue by MickScandalous** [ForgeEssentials/ForgeEssentials#2044]
I am trying to create a very large zone covering an entire forested area. When I define the area it says it is all set but when I move around it some parts will give the leave or entry message randomly as if the entire selection wasnt added to the zone. when I type /area to see the zones Cords they are correct though

**Comment by olee** [comment]
Please check again.
Maybe the length and width are correct, but the height of the area is not sufficient.
There is no way that areas stop working because of their size, because the code only checks the coordinates.
Also don't forget that it counts as "leaving a zone" if you enter a smaller (higher priority) area inside the larger area.

If you really cannot solve your problem by checking it again, please respond here or better on irc.

**Comment by MickScandalous** [comment]
There was no reason to close this as you just assumed I did something wrong rather than asking me for more info. I am having this issue and as I would have explained it seems like it is certain chunks in the area I defined that would have been not loaded due to how far away they were. I was wondering if this a part of it.

**Comment by olee** [comment]
@MickScandalous I just closed this issue as I am 99.9% sure, that the problem here was just a simple missunderstanding of the system and it's workings and that the problem is not a real issue in FE but more of a support question. That's why I asked you to reply here for more questions, feedback or details.
If - after getting more detailed information from you - it would become certain, that there is indeed a bug present, I would directly reopen this issue. Just because it is marked as "closed" does not mean we mods don't watch and converse on these topics any more.
Even then you don't have to open another issue regarding the same problem as we can always reopen issues.

Now for your problem: You could send me your permission file (if json format) or zipped folder (for flatfile format). That would allow me to see if there are maybe some conflicts in there causing your issues.

Also I'd like to ask for confirmation: Does your problem only occur with entry/exit messages and other permissions work just fine?

**Comment by MickScandalous** [comment]
[permissions.zip](https://github.com/ForgeEssentials/ForgeEssentials/files/187100/permissions.zip)

I have added the.zip of my permissions, My permissions so far appear to be working in the area "EnchantedForest" but as I walk or fly through the area I get the entry and Exit message making it seem like the zone has "Holes" in it or something. I can deny breaking blocks in that area and it will not let me break blocks so perms is working. Im just concerned on why the messages are acting up. Like I said it was such a large area that my FEpos1 would have naturally "Despawned" by the time I got to where I set fepos2 and I wonder if this has something to do with it

Im sorry I was mad eralier I misunderstood what was going on and I thought you were just blowing the topic off and moving on. Im not really sure what this IRC is

**Comment by olee** [comment]
Can you try flying through the area again and every time an enter/exit message appears, try using `/p list zones`. It will show you if there are any different areas defined at these places.
Also: Does only one message appear - i.e. "leaved area..." and only when you move a bit further "entered area..." appears?

**Comment by MickScandalous** [comment]
Im thinking it is due to plots also being made in the zone, I will have to delete those plots to find out
