### ISSUE TITLE
Has Chisels & bit  protection with ForgeEssentials?

### ISSUE THREAD

**Issue by pablojastorga** [ForgeEssentials/ForgeEssentials#2071]
Hi, I',m trying to deny Chiselsandbit generally in specific areas , to users , groups and nothing works . When used in debug mode the screen  display = false however can be use, break, place, interact, craft , etc.. 

I'm using forgeessentials-1.8-1.8.4.76-server   and forgeessentials-1.8-1.8.4.76-server  also tried forgeessentials-1.8-1.8.3.54-server

chiselsandbits-mc1.8-v1.6.5    and tried  chiselsandbits-1.5.1

any idea?  thanks!!

**Comment by spacebuilder2020** [comment]
It really depends how the tool works.  Some tools will use setblock to replace 1 block with another one.  This event is unstoppable without modifying the setBlock method.  And if you do add code, this can cause a significant amount of lag because everything uses the setBlock method internally.  In many cases the only way to protect against said tool is to prevent that tool from working in certain areas.

**Comment by Techjar** [comment]
Yeah it's going to be directly modifying a TE, so there's not really a way to protect it.

**Comment by olee** [comment]
That's not necessarily true.
Still @pablojastorga I'd advise you to instead disallow players from having the chisel in their inventory at all, which is way easier and already possible with FE.

**Comment by Zethalion** [comment]
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response @pablojastorga
