### ISSUE TITLE
Bug in shop signs logic

### ISSUE THREAD

**Issue by securitypedant** [ForgeEssentials/ForgeEssentials#2114]
I am using version 1.7.10-1.4.4.1177-server

I have a simple shop setup with 3 signs. Yet the logic isn't working. Look at the video below. I have 3 signs, each with item frames above. Sign 1 below item frame 1 sells item from frame 2. Sign 2 below item frame 2, sells item from item frame 3. Item frame 3 sign says the frame is already being used...

https://youtu.be/alFuA_CR4zE

**Comment by securitypedant** [comment]
I can give you access to server if you want to debug.

**Comment by spacebuilder2020** [comment]
Looks like if you create the shop (first click) before you place the frame but you have another frame on the wall it will use that one instead.

**Comment by spacebuilder2020** [comment]
@olee I am not sure if this is an intended feature or a bug

**Comment by olee** [comment]
@securitypedant If you want to place shop signs next to each other, you should **initialize** (first click on the sign as user with sufficient rights) them one after another starting from one side.

This is because FE will look around the sign to find any **unassigned** item frame.
If there are more than one, it can get confused.
IIRC it will look first above the sign and then continue to look at the sides.

Just remove the item from the item frames (which will destroy the shop but keep the sign) and then put in one item, click sign, put in next item, click next sign etc.
