### ISSUE TITLE
1.10.2 Crash with Ars Magica

### ISSUE THREAD

**Issue by ghost** [ForgeEssentials/ForgeEssentials#2233]
Incompatible with Ars Magica

http://pastebin.com/UF6iWUTA

**Comment by spacebuilder2020** [comment]
See #2180 

Ars Magica has been known to be incompatible in 1.7.10 and I am not really surprised that it is incompatible on 1.10.2

As far as fixing this incompatibility, I believe it is a low priority.

**Comment by Scratchman** [comment]
I'm setting up a server for 1.10.2 and currently testing mods, players have asked for ArsMagica2 to be included in the update and they've been testing it for the last week without any problems. Today i decided to add forgeessentials-1.10.2-10.1.109-server so i can set up perms and other server side admin stuff, but now the server crashes with both installed.

[Crash Report](https://pastebin.com/MndbCJ2T)

**Comment by Dehietyi** [comment]
I understand that this issue is a low priority. I do. However this same problem has existed for now 4 generations of Minecraft. I also understand that for a long time on 1.7.10 Ars Magica was not updating. That obviously makes finding/fixing the problem between developers much more difficult. However Ars is updating and Forge Essentials is also updating. Is there anyway we can get a line of communication going to fix this problem. At this point this issue has been going on for 3 years. People own cars for less time. TV shows start and end in less time. It would be nice to not have to choose between Ars and Essentials. If I had to make the decision Essentials wins every time; but I also have to consider the people that play on the servers and packs I build. After Bukkit and the issues surrounding that mess I thought Essentials would be gone for good so I was and am really happy you guys took this upon yourselves and Forge Essentials works really really well. Respectfully I ask that this 3 year old problem get fixed so it can work even better.

**Comment by spacebuilder2020** [comment]
As I recall, it was a bug on the ars magica side.  But if you can get the ars magica dev to participate, we will work on trying to fix it.

**Comment by Dehietyi** [comment]
Thank you spacebuilder2020. I had written a similar message to Ars on this subject and now have copied your response to that page in the hopes of getting a dialogue going. Seriously it's much appreciated.

**Comment by 811Alex** [comment]
For anyone that comes across this, I made a [fork of Ars Magica 2 for 1.10.2 with a separate server version](https://github.com/811Alex/ArsMagica2) (I just removed a bunch of client-side code and merged commits from different repositories into one).
I doubt I'll be updating it much, but if you really want both of these mods on your server, feel free to take a look and see if it works for you (it seems to work fine with forgeessentials-1.10.2-10.3.1378-server on my main server).

**Comment by Zethalion** [comment]
As we moved to 1.12.2, is this still an issue? Closing this issue in 7 days if no response @Scratchman @Dehietyi @811Alex @jgdovin

**Comment by 811Alex** [comment]
This is still an issue on 1.10.2, doubt it'll get fixed on AM2's side, but you can use it the way I proposed.
As for 1.12.2, [as far as I know](https://github.com/Growlith1223/ArsMagica2/issues/392), AM2's getting a rewrite, so it would probably be ok, when/if it gets released (I did find a fork that was supposed to be for 1.12.2, but I couldn't get it to run, so Idk).

**Comment by spacebuilder2020** [comment]
Closing since 1.10 is no longer supported.
