### ISSUE TITLE
1.10.2 server crashing on start up

### ISSUE THREAD

**Issue by Scratchman** [ForgeEssentials/ForgeEssentials#2260]
I'm currently in the process of updating our server to 1.10.2.

Forge-1.10.2-12.18.3.2254
forgeessentials-1.10.2-10.1.113-server
EngineersWorkshop-1.3.2-1.10.2

This is my first time setting up a forge server, up until now I've only set up forge/bukkit servers so I'm trying to learn how to server admin with just mods.

I've decided to move to FE to replace bukkit essentials in 1.10.2 but i've run into a conflict with FE and engineers workshop. I'm not sure if it's even possible to fix this on the server. I'm wondering if it's a fakeplayer issue.

Right now the only way to start the server is to remove FE, but I'd really like to keep it and Engineers workshop on the server.

[crashlog](https://pastebin.com/NgDz3FJ6)

**Comment by spacebuilder2020** [comment]
Update Forge Essentials.  That bug has already been fixed.

**Comment by Scratchman** [comment]
That is the latest 1.10.2 file version available on curse and [Forgeessentials.com](http://forgeessentials.com/2017/04/a-whole-bunch-of-releases/), forgeessentials-1.10.2-10.1.113

**Comment by spacebuilder2020** [comment]
This bug was fixed in build #115
Make sure to go to Jenkins to get the latest builds.
http://ci.forgeessentials.com/job/FE-1.10/

**Comment by Scratchman** [comment]
and if I try the experimental builds and find a bug am I going to be told I should only use posted versions?

**Comment by spacebuilder2020** [comment]
See the Readme
Specifically the part about reporting bugs.
----------------------------------------------
# Reporting bugs
Please follow these rules when reporting bugs:
- Update to the latest build from [Jenkins](http://ci.forgeessentials.com/job/FE) before reporting a bug.
- Check, if the bug was not already reported by using the search.
- Always attach logs to your reports if you encountered crashes.  
   If the client crashed, please also attach the client log if possible.
- For feature requests, we recommend asking about it on IRC firs.t
----------------------------------------------
Finally, as an additional note, Forge Essentials for 1.10 is still in an unstable state.  At this point in time, the latest Jenkins build will almost always be the most stable version
