### ISSUE TITLE
God (default: true) permission

### ISSUE THREAD

**Issue by StrikS** [ForgeEssentials/ForgeEssentials#2324]
The permission of the god is available to all, including guests and new groups.

**Comment by spacebuilder2020** [comment]
Closed for not following the rules on reporting bugs [here](https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs).

Also, the god command was never implemented in code but implemented from the legacy scripting system.  It is no longer in the current scripting system so this issue is outdated.
