### ISSUE TITLE
Crash on world unload

### ISSUE THREAD

**Issue by VenomiXeD** [ForgeEssentials/ForgeEssentials#2331]
As the title says. The world crashes when unloading a world. Example. Creating a world named "Test" and deleting it or /mw delete Test then the server crashes...
[crash-2017-12-11_18.34.54-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/1548852/crash-2017-12-11_18.34.54-server.txt)

Crash log
Version 1.7.10

**Comment by spacebuilder2020** [comment]
Please update your report to follow the bug report rules.
https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs

Based on your log, you seem to be running 1.4.6.1341

However, you are missing the server log.   The crash report only contains a small snippit of information.
In order to resolve your issue, at a minimum I need both the crash report and the full server log when the crash happened.

**Comment by VenomiXeD** [comment]
Ohh right. Sorry for late response to. But I will test it later.

**Comment by Zethalion** [comment]
Is this still an issue on 1.12.2 ? Closing this issue in 7 days if no respone @TheGamingLab

**Comment by VenomiXeD** [comment]
I'm running 1.7.10. But I bet that there's no support for it anymore. But this mod is great anyways.
