### ISSUE TITLE
[Question] Is it possible to create commands using permissions?

### ISSUE THREAD

**Issue by Solucent** [ForgeEssentials/ForgeEssentials#2353]
(Sorry about earlier, hit enter too early :'D)
But yes! This is probably a stupid question, but I was wondering if its possible to create a / command that is usable by all players?
The context is wanting players to be able to switch between two groups at their leisure. I'm aware you can set this up via command blocks, but I thought it'd be more convenient to have it as a command itself.
Is this feasible or am I going to have to learn how to code? ovo;

**Comment by olee** [comment]
> (Sorry about earlier, hit enter too early :'D)

You know you can EDIT your post? There's no need to open a new issue 😅

As for what you want to do:
You can use JS-Scripting module to write your own command which does whatever you want with access to quite a lot of features.
For example I wrote a command that prints the direction to the next diamond ore in the chat every second easily ;-)
You can the wiki about scripting [here](https://github.com/ForgeEssentials/ForgeEssentials/wiki/JS-Scripting)

Because of that I'm closing this issue and if you have further questions ask here or probably better in our Discord server.
