### ISSUE TITLE
Orbis World Editor gamemode 4 issue

### ISSUE THREAD

**Issue by Adam-R-Kaminski** [ForgeEssentials/ForgeEssentials#2377]
Orbis: https://minecraft.curseforge.com/projects/orbis
./gamemode 4 command instead of switching me to orbis mode just switches me to survival mode.
This issue appeared only after installing FE on the server.

**Comment by Zethalion** [comment]
Use /toggledesigner instead

**Comment by spacebuilder2020** [comment]
Forge Essentials overwrites the game-mode command to provide additional functionality, so if Obris does so as well that is probably causing a problem.  We can look into providing Orbis compatibility at a later date.

**Comment by spacebuilder2020** [comment]
This is a bug in Orbis's code.
https://git.gildedgames.com/GildedGames/Orbis/blob/master/src/main/java/com/gildedgames/orbis/common/OrbisDeveloperModeEvents.java#L32

Orbis is only doing it's gamemode 4 logic if the class is CommandGameMode.  Since Forge Essentials overwrites the Gamemode command, this never gets called.

Orbis should update their code so it supports overwriting the gamemode command. I would recommend them replacing line 32 with
 `if ("gamemode".equals(event.getCommand().getName()))`
to support overwriting the gamemode command.
