### ISSUE TITLE
No clip permission still doesn't work

### ISSUE THREAD

**Issue by docteurzoidberg** [ForgeEssentials/ForgeEssentials#2466]
On latest .67 build
https://i.imgur.com/O480rU8.png

modlist: irrelevant

**Comment by docteurzoidberg** [comment]
https://i.imgur.com/6OwXAXi.png

**Comment by spacebuilder2020** [comment]
Modlist is always relevant. Especially in the case where it did not work for you as op.  That probably means that something is breaking FE.

**Comment by docteurzoidberg** [comment]
check screenshots please. my permissions are OK, mods: irrelevant for this kind of fix, and i can assure you 3000% that the permission still doesn"t work as op

**Comment by docteurzoidberg** [comment]
btw two ore more people are experiencing exactly the same thing on discord these days

**Comment by spacebuilder2020** [comment]
That issue was resolved.
![image](https://user-images.githubusercontent.com/8677143/66247534-defea480-e6da-11e9-9572-de272eb99bd6.png)

I am thinking your issue is related to your setup.  That is why we need your modlist to resolve your issue.  Without it, I can't resolve your issue as much as I would like to.
