### ISSUE TITLE
[1.12.2] [BUG] Crash on a server.

### ISSUE THREAD

**Issue by MagmaSlime123** [ForgeEssentials/ForgeEssentials#2548]
**Initial Steps**
- [ X] I have updated to the latest build from Jenkins before reporting a bug
- [X] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [X] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log
- [X] Also, attached are the client logs (if applicable)
[ForgeEssentials.zip](https://github.com/ForgeEssentials/ForgeEssentials/files/4919862/ForgeEssentials.zip)
[latest.log](https://github.com/ForgeEssentials/ForgeEssentials/files/4919870/latest.log)
I have no clue how to obtain a debug log.
There is no modlist txt.

[crash-2020-07-14_10.55.51-server.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/4919881/crash-2020-07-14_10.55.51-server.txt)

**Describe the bug**
Server crashes.

**To Reproduce**
Start a Forge server with this mod on it.

**Expected behavior**
Everything starting up and working...

**Screenshots**
![image](https://user-images.githubusercontent.com/51277766/87448588-e4194a00-c5b0-11ea-80f2-38bf672ed5c0.png)

**Desktop (please complete the following information):**
Ask GameServerSupply.

**Additional context**

I bet you'll simply utterly ignore all of this tbh... I'm not gonna use something that doesn't work.

**Comment by spacebuilder2020** [comment]
Thanks for bringing this to our attention.  In a normal setup, FE will start up and work.  However, it seems that hibernate is throwing an error and crashing the mod.

Try running without Magma.  Forge Essentials is not designed to work with Thermos based hybrid forge systems.

**Comment by MagmaSlime123** [comment]
There's pretty much no stable Forge/Spigot hybrid software anywhere. Magma is the only one I know that is somewhat working.

**Comment by spacebuilder2020** [comment]
Forge Essentials was never designed to run in a hybrid configuration with Spigot.  Forge Essentials is designed for a pure forge run.   That being said, I am willing to spend some time troubleshooting Magma cause it does seem to be becoming more popular.

However, at this point in time, it is not expected for Forge Essentials to function with any Forge/Spigot hybrid.

This is mostly because Cauldron / Thermos based distributions uses patching to modify a large number of minecraft classes.  This patching makes it incompatible with any other mod that needs to make source code modifications as well as mods that need to call minecraft methods.  (I had to make a custom build of thermos one on a server I ran to get hardcore ender expansion to not crash due to thermos renaming a minecraft class method).

If you still want to use Forge/Spigot, I would recommend using a different Essentials mod (Bukkit Essentials) that is designed for Bukkit.

**Comment by MagmaSlime123** [comment]
Oh.

Well, if Magma support is ever added/fixed, then let me know. I'll close this if needed.

**Comment by spacebuilder2020** [comment]
Alright, just be aware it is a very low priority right now cause I am the only FE developer left and am fully consumed with work.

However, If we do end up adding support, I will be sure to let you know.

I will leave this open because it is still a crash and I want to address it at some point in the future.

**Comment by kingdevnl** [comment]
I will have a look in this issue, And start debugging it.

I'm one of the authors of Magma

**Comment by spacebuilder2020** [comment]
Thanks, it will very useful to have FE functional with Magma

**Comment by spacebuilder2020** [comment]
Closing as at the current time, support for Magma is not in the cards!
