### ISSUE TITLE
[1.12.2] [BUG]

### ISSUE THREAD

**Issue by DesolateIntention** [ForgeEssentials/ForgeEssentials#2558]
**Initial Steps**
- [Yes] I have updated to the latest build from Jenkins before reporting a bug
- [Yes] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [Debug is too heavy] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log

**Describe the bug**
When using `p user (non-existent user)`, a weird exception thing shows up, instead of a proper error message.
**To Reproduce**
**| 1 |** Type `p user KAJEWFDOJAWDOIJAWODJAWOID()()()A(W =D(UAW=D()AW)(`.
**| 2 |** See error.

**Expected behavior**
A proper error message.

**Desktop (please complete the following information):**
 - OS: Windows 7.
 - Browser: Chrome.
 - Version: ?
[latest.log](https://github.com/ForgeEssentials/ForgeEssentials/files/5228874/latest.log)
[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/5228880/modlist.txt)

**Comment by spacebuilder2020** [comment]
I think this is because the username code is sending a request to mojang if a user doesn't exist.  It seems Mojang is returning a 400 error when receiving a username with this junk data.

https://api.mojang.com/users/profiles/minecraft/UHIEAUHDOI)AUHFOI(BHFOI=EABHF(OYEAWHDO(YEAHGFYEH

I can fix the code to behave gracefully when this happens.

**Comment by DesolateIntention** [comment]
Thanks.
