### ISSUE TITLE
Console (SSH) loses permission to basic management cmds after installing FE

### ISSUE THREAD

**Issue by HaloSense** [ForgeEssentials/ForgeEssentials#2592]
I am using Mohist to start a server. Version: 1.12.2_242
I have installed multiple mods. Attachment is my modlist.txt.

The problem is that after I start the server with FE, at the final steps of startup, the console says the aliases of some commands are registered twice, and have deleted one of them. And after the server fully started up, when I try to stop the server using command /stop with SSH, the console (SSH) tells me that I do not have permission to the command. Same thing happens with commands such as /op, /deop, /ban, etc. 

I am using FTB Utilities, so as instructed on this page: https://github.com/ForgeEssentials/ForgeEssentials/wiki/FTBU-Compatibility-Guide, I have adjusted the ftbutilities.cfg.

[modlist.txt](https://github.com/ForgeEssentials/ForgeEssentials/files/6794741/modlist.txt)

**Comment by spacebuilder2020** [comment]
Well, 1) I am not sure how you did it but somehow you managed to bypass our issue template for bug reports.  Thus your report is invalid.
Please update following the rules listed on the readme! https://github.com/ForgeEssentials/ForgeEssentials#reporting-bugs

2) Mohist is not a supported configuration because it is a fork / etc of Cauldron.  Forge Essentials does not support Cauldron or it's derivatives

3) the Stop command is not overridden but regardless, the commands FE overwrites are just it's own versions of existing commands. (Excluding a conflict between a mod command with the same name).

4) By SSH, I assume you mean that you are in the console via linux command line and not some other form

**Comment by HaloSense** [comment]
Okay. Thanks for helping. I did not report this as a bug because I am not sure whether it is one. As to how I bypassed the issue template, after I click on New Issue button, the browser comes to a page where I choose to report a bug or give advice for new features, and there's a "Don’t see your issue here? Open a blank issue." written at the bottom and a link to a page where I can fill in blank issues.

So, since I still want to use essentials in my server, what do you suggest me to use/do? Should I use the original EssentialsX plugin or do I switch to another server-side configuration?

**Comment by spacebuilder2020** [comment]
Forge Essentials is not in any way related to Bukkit Essentials.  If you want to use Forge Essentials, you need a pure forge environment.  If you want plugins, use EssentialsX.  As for the issue template, I will be fixing that in a future commit.
