### ISSUE TITLE
[1.12.2] [BUG] Forge Essentials does not allow the mod to run the command.

### ISSUE THREAD

**Issue by Kellmyru** [ForgeEssentials/ForgeEssentials#2665]
**Initial Steps**
- [x] I have updated to the latest build from [Discord](https://discord.gg/FNRQjmr) in the [#dev-builds](https://discord.com/channels/264189448273526786/1149096704231100426) channel before reporting a bug
- [x] I have checked, if the bug was not already reported by using the [search](https://github.com/ForgeEssentials/ForgeEssentials/issues?q=).
- [ ] Attached is my ForgeEssentials/modlist.txt, my latest.log, and my debug.log
- [ ] Also, attached are the client logs (if applicable)

**Describe the bug**
I am using Forge Server 1.12.2. There is a ReMoney mod, the mod has a block that, when the player logs in, uses certain commands to charge currency from another mode [Oxygen mod]. In pure Forge, without ForgeEssentials, everything works fine and there are no problems. And in the presence of ForgeEssentials, the command seems to be blocked by ForgeEssentials and does not reach the server. It seems that ForgeEssentials is somehow blocking the execution of the command inside the mod. Please help me figure out how to fix this. I am attaching ReMoney Mod and also using this version of ForgeEssentials.

**To Reproduce**
1. Install Forge Essentials and ReMoney mod and Oxygen modifications on the Forge server. [Oxygen Core and Oxygen Shop https://legacy.curseforge.com/minecraft/mc-mods/oxygen-core }
2. Place a block of money in the form of a stone with a Euro sign and break it in any of the modes (Survival/Creative)
3. Check your money balance inside the Oxygen mod.
4. You can also install an ATM block and make a deposit of any of the bills (packs are not accepted). It will be visible that the command is executed, but the balance is not replenished.
5. Without ForgeEssentials everything works fine and stable.

**Expected behavior**
I would like to understand, perhaps it is necessary to give the privilege to groups so that the command is executed correctly, or to make certain changes in ForgeEssentials if it does not skip the execution of the command.

**Desktop (please complete the following information):**
 - OS: Winows 10
 - Browser Chrome
 - Version last

**Additional context**
ReMoney mod: https://www.dropbox.com/scl/fi/ks4qr8sxuubpig5pahcj2/Remoney18.jar?rlkey=upwsl5ny1fvifky87ef2gtk1u&dl=0

**Comment by spacebuilder2020** [comment]
This is probably a permissions issue at a first glance.  I would recommend first using `/p debug` and run this command while near (within 32 blocks) a non opped player.  (or even the money terminal assuming that it is the mod block that doesn't have permission).  When the command is enabled, it should show you all kinds of command spam including what nodes are being denied and what the username is that is denied.  (in the case of the money mod, it is a fake player).  You will need to grant access to that user.  (Also, if fake players is set up right, all fake players should be in the `_NPC_` group in 1.12)

**Comment by spacebuilder2020** [comment]
(however, some blocks like command blocks report their position as 0,0 so keep that in mind too)

**Comment by Kellmyru** [comment]
I'll try to run Debug mode and send you the result. Currently, there are only categories  `_NPC_` and `_FACEPLAYER_.`

**Comment by Kellmyru** [comment]
![image](https://github.com/ForgeEssentials/ForgeEssentials/assets/112304022/e83fe72d-f283-4ffd-ad52-9bf1368dcd77)
I understand correctly that NPCs need to be given access to the command `command.oxygenop` ?

**Comment by Kellmyru** [comment]
![image](https://github.com/ForgeEssentials/ForgeEssentials/assets/112304022/c8f61006-ca08-46d1-984e-addf71f6bc94)
I found this entry and I have a feeling that this is exactly how the permission system perceives it, should I add permission to this particular object or to the entire `_NPC_` group?

**Comment by Kellmyru** [comment]
Thank you, it seems like the problem is solved and everything is working.

**Comment by spacebuilder2020** [comment]
Sweet, I am glad.   If you have other issues, feel free to ask on our [discord](https://discord.gg/FNRQjmr).

**Comment by spacebuilder2020** [comment]
yea.  However, something looks off cause this NPC doesn't have a name.  (In 1.12, FE will take the name and append `$NPC_` since some mods were setting the npc's name to the owning player and that was messing up permissions.  Since it is just '$NPC_', it may still cause you issues if another block also has an NPC without a name.  This may cause a duplicate entry, I added code to allow renaming the UUID part to prevent this but it still happens from time to time and that was why I just forced every NPC to have a prefix.  This won't effect the functionality of the mod but when you boot the server up again, it will crash.)

**Comment by spacebuilder2020** [comment]
Finally, can you post a link to the Curseforge or Modrinth site where this mod came from.  That will help if I have to try and fix a mod compatibility.  Lastly, if a mod is not open or visual source, my policy is that the requester needs to reach out to the mod owner to get assistance first and if they don't respond, we will not do anything to fix it because we want to respect the mod owners rights and will not decompile or do any remote debugging to fix any mod that does not provide source code. (Coordination is required in the case of closed source, if we don't get that, we can not proceed.)
